version: "3.1"
services:

  postgres:
    image: postgres:11.1-alpine
    container_name: api-postgres-test
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=api
    ports:
      - "5430:5432"
    
  test:
    container_name: api-test
    depends_on:
      - postgres
    working_dir: /application
    environment:
      - PHP_IDE_CONFIG=serverName=test.api
    build:
      context: ./phpdocker/test
      dockerfile: Dockerfile
    volumes:
      - .:/application:delegated
      - ./vendor:/application/vendor:cached
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini


