version: "3.2"
services:

  postgres:
    image: postgres:11.1-alpine
    container_name: api-postgres
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=api
      - COMPOSE_PROJECT_NAME=symfony-api
    ports:
      - "5432:5432"

  php-fpm:
    build: docker/dev/php-fpm
    environment:
      - PHP_IDE_CONFIG=serverName=API
      - COMPOSE_PROJECT_NAME=symfony-api
    container_name: api-php-fpm
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./docker/dev/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  composer-installation:
    container_name: api-composer-installation
    image: composer
    volumes:
      - ./:/application
    command: composer install --ignore-platform-reqs

  webserver:
    image: nginx:alpine
    container_name: api-webserver
    depends_on:
      - postgres
      - php-fpm
    environment:
      - COMPOSE_PROJECT_NAME=symfony-api
    working_dir: /application
    volumes:
        - .:/application
        - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"

  mailhog:
    environment:
      - COMPOSE_PROJECT_NAME=symfony-api
    container_name: api-mail
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"